[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello = "HCRfNNCXTfj8k78NoBvPjpH9zWjFmizPDK6ovBNt1Bvt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kienle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
